# Generated by Django 3.0.4 on 2020-04-23 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicaciones', '0012_auto_20200408_0435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aplicacion',
            name='ind_estado',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Inactivo'), (1, 'Activo')], default=1),
        ),
    ]
