# Generated by Django 3.0.4 on 2020-04-23 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companias', '0003_auto_20200423_2351'),
        ('miscelaneosdet', '0011_auto_20200423_2351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_sucursal', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=500)),
                ('telefono1', models.CharField(max_length=20)),
                ('telefono2', models.CharField(max_length=20, null=True)),
                ('telefax1', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('ind_estado', models.PositiveSmallIntegerField(choices=[(1, 'Activo'), (0, 'Inactivo')], default=1)),
                ('ult_usuario', models.CharField(max_length=100)),
                ('ult_fecha', models.DateTimeField(auto_now=True)),
                ('ult_equipo', models.CharField(max_length=200)),
                ('ult_ip', models.GenericIPAddressField(null=True)),
                ('id_compania', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companias.Compania')),
                ('id_miscdet_gruposucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miscelaneosdet.DetMiscelaneo')),
            ],
            options={
                'db_table': 'si_maestro_sucursales',
            },
        ),
    ]
