# Generated by Django 3.0.4 on 2020-04-08 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_moneda', models.CharField(max_length=20)),
                ('siglas_moneda', models.CharField(max_length=4, unique=True)),
                ('tipo_moneda', models.CharField(max_length=2)),
                ('ind_estado', models.PositiveSmallIntegerField(choices=[(0, 'Inactivo'), (1, 'Activo')], default=1)),
                ('ult_usuario', models.CharField(max_length=100)),
                ('ult_fecha', models.DateTimeField(auto_now=True)),
                ('ult_equipo', models.CharField(max_length=200)),
                ('ult_ip', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'si_maestro_monedas',
            },
        ),
    ]
