# Generated by Django 3.0.4 on 2020-04-06 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_municipio', models.CharField(max_length=200)),
                ('ind_estado', models.PositiveSmallIntegerField(choices=[(0, 'Inactivo'), (1, 'Activo')], default=1)),
                ('ult_usuario', models.CharField(max_length=100)),
                ('ult_fecha', models.DateTimeField(auto_now=True)),
                ('ult_equipo', models.CharField(max_length=200)),
                ('ult_ip', models.CharField(max_length=200)),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estados.Estado')),
            ],
            options={
                'db_table': 'si_maestro_municipios',
            },
        ),
    ]
