# Generated by Django 3.0.4 on 2020-04-07 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('municipios', '0007_auto_20200407_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipio',
            name='ind_estado',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Activo'), (0, 'Inactivo')], default=1),
        ),
    ]
