# Generated by Django 3.0.4 on 2020-04-07 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('miscelaneos', '0002_auto_20200407_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetMiscelaneo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_detalle', models.CharField(max_length=12)),
                ('desc_detalle', models.CharField(max_length=150)),
                ('ind_estado', models.PositiveSmallIntegerField(choices=[(1, 'Activo'), (0, 'Inactivo')], default=1)),
                ('ult_usuario', models.CharField(max_length=100)),
                ('ult_fecha', models.DateTimeField(auto_now=True)),
                ('ult_equipo', models.CharField(max_length=200)),
                ('ult_ip', models.CharField(max_length=200)),
                ('id_miscelaneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miscelaneos.Miscelaneo')),
            ],
            options={
                'db_table': 'si_maestro_miscelaneos_det',
            },
        ),
    ]
