# Generated by Django 3.0.4 on 2020-04-07 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aplicaciones', '0003_auto_20200407_0043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Miscelaneo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_maestro', models.CharField(max_length=12)),
                ('nombre_maestro', models.CharField(max_length=100)),
                ('desc_maestro', models.CharField(max_length=150, null=True)),
                ('ind_estado', models.PositiveSmallIntegerField(choices=[(0, 'Inactivo'), (1, 'Activo')], default=1)),
                ('ult_usuario', models.CharField(max_length=100)),
                ('ult_fecha', models.DateTimeField(auto_now=True)),
                ('ult_equipo', models.CharField(max_length=200)),
                ('ult_ip', models.CharField(max_length=200)),
                ('id_aplicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicaciones.Aplicacion')),
            ],
            options={
                'db_table': 'si_maestro_miscelaneos',
            },
        ),
    ]
