# Generated by Django 3.0.4 on 2020-04-07 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miscelaneos', '0003_auto_20200407_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miscelaneo',
            name='cod_maestro',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
