# Generated by Django 3.0.4 on 2020-04-24 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('miscelaneosdet', '0012_auto_20200424_0101'),
        ('personas', '0011_auto_20200424_0101'),
        ('ciudades', '0024_auto_20200424_0101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion_secuencia', models.CharField(max_length=4)),
                ('direccion', models.CharField(max_length=400)),
                ('referencia_direccion', models.CharField(max_length=200)),
                ('telef_contacto', models.CharField(max_length=20)),
                ('telefax', models.CharField(max_length=20)),
                ('es_cobranza', models.BooleanField(default=False)),
                ('es_domicilio', models.BooleanField(default=False)),
                ('es_remision', models.BooleanField(default=False)),
                ('es_principal', models.BooleanField(default=False)),
                ('es_otros', models.BooleanField(default=False)),
                ('ind_estado', models.PositiveSmallIntegerField(choices=[(0, 'Inactivo'), (1, 'Activo')], default=1)),
                ('ult_usuario', models.CharField(max_length=100)),
                ('ult_fecha', models.DateTimeField(auto_now=True)),
                ('ult_equipo', models.CharField(max_length=200)),
                ('ult_ip', models.GenericIPAddressField(null=True)),
                ('id_ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciudades.Ciudad')),
                ('id_miscdet_situaciondomicilio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones_direccion_id_miscdet_nacionalidad', to='miscelaneosdet.DetMiscelaneo')),
                ('id_miscdet_tipodireccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones_direccion_id_miscdet_edocivil', to='miscelaneosdet.DetMiscelaneo')),
                ('id_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.Persona')),
            ],
            options={
                'db_table': 'si_maestro_direcciones',
            },
        ),
    ]
