# Generated by Django 3.0.4 on 2020-04-23 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grupocentrocostos', '0002_auto_20200423_2147'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubGrupoCentroCosto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_subgrupo', models.CharField(max_length=20, unique=True)),
                ('desc_subgrupo', models.CharField(max_length=200)),
                ('ind_estado', models.PositiveSmallIntegerField(choices=[(0, 'Inactivo'), (1, 'Activo')], default=1)),
                ('ult_usuario', models.CharField(max_length=100)),
                ('ult_fecha', models.DateTimeField(auto_now=True)),
                ('ult_equipo', models.CharField(max_length=200)),
                ('ult_ip', models.GenericIPAddressField(null=True)),
                ('id_grupocentrocosto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grupocentrocostos.GrupoCentroCosto')),
            ],
            options={
                'db_table': 'si_maestro_subgrupocentrocostos',
            },
        ),
    ]
