# Generated by Django 3.0.4 on 2020-04-08 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('municipios', '0009_auto_20200408_0049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parroquia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_parroquia', models.CharField(max_length=255)),
                ('ind_estado', models.PositiveSmallIntegerField(choices=[(0, 'Inactivo'), (1, 'Activo')], default=1)),
                ('ult_usuario', models.CharField(max_length=100)),
                ('ult_fecha', models.DateTimeField(auto_now=True)),
                ('ult_equipo', models.CharField(max_length=200)),
                ('ult_ip', models.CharField(max_length=200)),
                ('id_municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='municipios.Municipio')),
            ],
            options={
                'db_table': 'si_maestro_parroquias',
            },
        ),
    ]
