# Generated by Django 3.0.4 on 2020-04-08 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parroquias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parroquia',
            name='ind_estado',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Activo'), (0, 'Inactivo')], default=1),
        ),
        migrations.AlterField(
            model_name='parroquia',
            name='ult_ip',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
