# Generated by Django 3.0.4 on 2020-04-06 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('municipios', '0002_auto_20200406_2225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_ciudad', models.CharField(max_length=200)),
                ('cod_postal', models.CharField(max_length=100)),
                ('ind_estado', models.PositiveSmallIntegerField(choices=[(1, 'Activo'), (0, 'Inactivo')], default=1)),
                ('ind_capital', models.PositiveSmallIntegerField(choices=[(0, 'No'), (1, 'Si')], default=0)),
                ('ult_usuario', models.CharField(max_length=100)),
                ('ult_fecha', models.DateTimeField(auto_now=True)),
                ('ult_equipo', models.CharField(max_length=200)),
                ('ult_ip', models.CharField(max_length=200)),
                ('id_municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='municipios.Municipio')),
            ],
            options={
                'db_table': 'si_maestro_ciudades',
            },
        ),
    ]
