# Generated by Django 3.0.4 on 2020-04-06 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciudades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudad',
            name='ind_capital',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Si'), (0, 'No')], default=0),
        ),
        migrations.AlterField(
            model_name='ciudad',
            name='ind_estado',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Inactivo'), (1, 'Activo')], default=1),
        ),
    ]
