# Generated by Django 3.0.4 on 2020-04-07 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciudades', '0005_auto_20200407_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudad',
            name='ind_estado',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Activo'), (0, 'Inactivo')], default=1),
        ),
    ]
