# Generated by Django 3.0.4 on 2020-04-07 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciudades', '0007_auto_20200407_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudad',
            name='ind_capital',
            field=models.PositiveSmallIntegerField(choices=[(0, 'No'), (1, 'Si')], default=0),
        ),
    ]
