# Generated by Django 3.0.4 on 2020-04-08 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciudades', '0014_auto_20200408_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudad',
            name='ind_capital',
            field=models.PositiveSmallIntegerField(choices=[(0, 'No'), (1, 'Si')], default=0),
        ),
    ]
