# Generated by Django 3.0.4 on 2020-04-08 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciudades', '0016_auto_20200408_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudad',
            name='ind_capital',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Si'), (0, 'No')], default=0),
        ),
    ]
