# Generated by Django 3.0.4 on 2020-04-08 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0008_auto_20200408_0435'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compania',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_compania', models.CharField(max_length=20, unique=True)),
                ('doc_fiscal', models.CharField(max_length=20, unique=True)),
                ('pagina_web', models.CharField(max_length=200)),
                ('desc_compania', models.CharField(max_length=250)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('telef_contact_1', models.CharField(max_length=20)),
                ('telef_contact_2', models.CharField(max_length=20)),
                ('telef_fax', models.CharField(max_length=20)),
                ('telef_movil', models.CharField(max_length=20)),
                ('logo_compania', models.ImageField(upload_to='companias')),
                ('direccion', models.CharField(max_length=250)),
                ('tipo_compania', models.CharField(max_length=2)),
                ('certificado_reg', models.CharField(max_length=200)),
                ('email_corp', models.CharField(max_length=20)),
                ('ind_estado', models.PositiveSmallIntegerField(choices=[(1, 'Activo'), (0, 'Inactivo')], default=1)),
                ('ult_usuario', models.CharField(max_length=100)),
                ('ult_fecha', models.DateTimeField(auto_now=True)),
                ('ult_equipo', models.CharField(max_length=200)),
                ('ult_ip', models.GenericIPAddressField(null=True)),
                ('id_persona_jefe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companias_compania_id_persona_jefe', to='personas.Persona')),
                ('id_persona_resp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companias_compania_id_persona_resp', to='personas.Persona')),
            ],
            options={
                'db_table': 'si_maestro_companias',
            },
        ),
    ]
